apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: hello-world
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 512Mi
